# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tuner.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 229)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.tuningBox = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        self.tuningBox.setObjectName("tuningBox")
        self.tuningBox.addItem("")
        self.tuningBox.addItem("")
        self.verticalLayout_7.addWidget(self.tuningBox)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.oneSeconds = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.oneSeconds.setObjectName("oneSeconds")
        self.verticalLayout_6.addWidget(self.oneSeconds)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.firstString = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.firstString.setObjectName("firstString")
        self.verticalLayout_6.addWidget(self.firstString)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.twoSeconds = QtWidgets.QSpinBox(self.verticalLayoutWidget_5)
        self.twoSeconds.setObjectName("twoSeconds")
        self.verticalLayout_5.addWidget(self.twoSeconds)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.twoString = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.twoString.setObjectName("twoString")
        self.verticalLayout_5.addWidget(self.twoString)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.threeSeconds = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.threeSeconds.setObjectName("threeSeconds")
        self.verticalLayout_4.addWidget(self.threeSeconds)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.threeString = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.threeString.setObjectName("threeString")
        self.verticalLayout_4.addWidget(self.threeString)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.fourSeconds = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.fourSeconds.setObjectName("fourSeconds")
        self.verticalLayout_3.addWidget(self.fourSeconds)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.fourString = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.fourString.setObjectName("fourString")
        self.verticalLayout_3.addWidget(self.fourString)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.fiveSeconds = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.fiveSeconds.setObjectName("fiveSeconds")
        self.verticalLayout_2.addWidget(self.fiveSeconds)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.fiveString = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.fiveString.setObjectName("fiveString")
        self.verticalLayout_2.addWidget(self.fiveString)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sixSeconds = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sixSeconds.setObjectName("sixSeconds")
        self.verticalLayout.addWidget(self.sixSeconds)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.sixString = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sixString.setObjectName("sixString")
        self.verticalLayout.addWidget(self.sixString)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.volumeSlide = QtWidgets.QSlider(self.splitter_3)
        self.volumeSlide.setMinimum(1)
        self.volumeSlide.setMaximum(10)
        self.volumeSlide.setSliderPosition(3)
        self.volumeSlide.setOrientation(QtCore.Qt.Vertical)
        self.volumeSlide.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.volumeSlide.setTickInterval(1)
        self.volumeSlide.setObjectName("volumeSlide")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.splitter_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tuningBox.activated['int'].connect(self.tuningBox.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tuner"))
        self.label_13.setText(_translate("MainWindow", "Tuning "))
        self.tuningBox.setToolTip(_translate("MainWindow", "Change the tuning mode"))
        self.tuningBox.setItemText(0, _translate("MainWindow", "Standard Tuning"))
        self.tuningBox.setItemText(1, _translate("MainWindow", "D# Standard"))
        self.label_11.setText(_translate("MainWindow", "Duration (s)"))
        self.firstString.setText(_translate("MainWindow", "Play"))
        self.label_12.setText(_translate("MainWindow", "1st String (hi E)"))
        self.label_9.setText(_translate("MainWindow", "Duration (s)"))
        self.twoString.setText(_translate("MainWindow", "Play"))
        self.label_10.setText(_translate("MainWindow", "2nd String (B)"))
        self.label_7.setText(_translate("MainWindow", "Duration (s)"))
        self.threeString.setText(_translate("MainWindow", "Play"))
        self.label_8.setText(_translate("MainWindow", "3rd String (G)"))
        self.label_5.setText(_translate("MainWindow", "Duration (s)"))
        self.fourString.setText(_translate("MainWindow", "Play"))
        self.label_6.setText(_translate("MainWindow", "4th String (D)"))
        self.label_3.setText(_translate("MainWindow", "Duration (s)"))
        self.fiveString.setText(_translate("MainWindow", "Play"))
        self.label_4.setText(_translate("MainWindow", "5th String (A)"))
        self.label.setText(_translate("MainWindow", "Duration (s)"))
        self.sixString.setText(_translate("MainWindow", "Play"))
        self.label_2.setText(_translate("MainWindow", "6th String (low E)"))
        self.volumeSlide.setToolTip(_translate("MainWindow", "Adjust Volume"))
